version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram-db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mariiavi/foodgram_backend:latest
    container_name: foodgram-backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mariiavi/foodgram_frontend:latest
    container_name: foodgram-front
    command: sh -c "cp -r /app/build/. /static/ && mv /static/static/* /static/"
    volumes:
      - static:/static
    restart: "no"

  nginx:
    image: mariiavi/foodgram_gateway:latest
    container_name: foodgram-proxy
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    restart: always
    depends_on:
      - backend
      - frontend